# POST http://localhost:3000/auth/login
# content-type: application/json

# {
#     "username": "maria",
#     "password": "guess"
# };


GET http://localhost:3000/visitor/visitor-stats/101


POST http://localhost:3000/visitor/add-visitor
content-type: application/json

{
    "name": "Testing Another",
    "password": "test",
    "email": "testing@example.com",
    "role": "visitor",
    "mobile": "1234567890",
    "purpose": "visiting flat for food delivery",
    "apartment_number": "201"
}
